scrape_configs:
    - job_name: node
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:9100']
            labels:
                instance: ${instance_name}
    - job_name: blackbox
      scrape_interval: 5s
      metrics_path: /probe
      params:
          module: [tcping]
      file_sd_configs:
          - files:
                - /usr/local/bin/vmagent/endpoint.yml
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: instance
            replacement: ${instance_name}
          - target_label: __address__
            replacement: localhost:9115
